### ISSUE TITLE
Support Ability ID for Images

### ISSUE THREAD

**Issue by pjmagee** [pjmagee/swtor-caster#1]
Unique images do not work for generic abilities or abilities with the same name from different classes. 

For example the Taunt ability icon is different for all classes, the Guard ability icon is different for all classes, but they share the same name, so when using the ability, only one of the icons can be used as the ability name is not unique across multiple classes.

**Comment by pjmagee** [comment]
This was completed with the help of @swtorpotato

**Comment by cemeai** [comment]
Is there any way i can get the ability images and maybe the classes icons?

**Comment by pjmagee** [comment]
It's not 100% up to date, but this might help:    
 https://github.com/pjmagee/swtor-caster/blob/master/src/SwtorCaster/JediPediaImages.zip

You can also checkout TOR Community website or JediPedia Websites.

**Comment by cemeai** [comment]
thx ill check on those places for the updated versions, meanwhile that helps so much
