### ISSUE TITLE
multiple ability events in the logger window

### ISSUE THREAD

**Issue by defurious** [pjmagee/swtor-caster#14]
Encountered this while testing out marksmanship sniper. Mainly happens with penetrating blasts which would show up more than once on the logger. Usually twice in a row but on one occasion showed up 4 times. attached a screenshot and log. pardon the length of the log, was parsing for quite a while before i noticed the bug. it happens early on anyway. I did switch specs to virulence and engineering later on but i haven't checked to see if the bug also happens to cull and series of shots.
![2015-11-16-0059-27 flv_20151116_133557 578](https://cloud.githubusercontent.com/assets/15865578/11174981/65bda610-8c67-11e5-9bb2-3fd3e85a654f.jpg)
[combat_2015-11-16_00_36_50_716833.txt](https://github.com/pjmagee/swtor-caster/files/35180/combat_2015-11-16_00_36_50_716833.txt)

**Comment by pjmagee** [comment]
You have flash on critical hits enabled. Penetrating blasts has 3 or 4 hits if I'm correct. If these were critical hits then It shows them. 

Do you think maybe it should only show 1 even though there are more than one hit?

**Comment by defurious** [comment]
That was what i expected given that it was designed to show what ability was activated. Now that i understand it better i dont really have a problem with it. For the purpose of creating video guides, though, it might be best if it was optional to show each tick or crit on a channeled ability. —

**Comment by pjmagee** [comment]
I'll work on adding an option for this so that you can disable it showing per tick.

**Comment by pjmagee** [comment]
Actually. We have a weird situation here. 

If I am to add an option showing per tick. Then we would never see the critical hit of a casted ability which may crit on multiple hits. 

I think the best option is to just untick the "Flash on critical hits" option. I think the behaviour of SWTOR Caster is correct. Because if you cancel the ability then it does not display any more of the critical hits, since it's an interrupted cast.

**Comment by pjmagee** [comment]
Just so you know, the show critical hit is an optional setting already! It's under the Main Settings.

**Comment by defurious** [comment]
That will do just fine, thanks. —

**Comment by pjmagee** [comment]
Flashing on critical hits has been removed from SWTOR Caster.
