### ISSUE TITLE
Border around abilities

### ISSUE THREAD

**Issue by ahmetabdi** [pjmagee/swtor-caster#6]
Attack, Defensive, Support skills

Red, Yellow, Green? Customizable?

**Comment by pjmagee** [comment]
Would need to add these to the individual images because the images have alpha. Something like `42342940342.DEF.png` ?

**Comment by pjmagee** [comment]
Or we would need a Table in Settings Page....where you provide Combat ID and then input this into the Table Column "ID" and then "Border" column select a colour maybe?

**Comment by ahmetabdi** [comment]
Harder than I anticipated, would require manual sorting through each ability.

**Comment by pjmagee** [comment]
This is done.

**Comment by ahmetabdi** [comment]
Thanks, I really appreciate all your work.
Keep it up. :+1:
